name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      bump_rule:
        description: 'Version bump rule (major/minor/patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  validate:
    uses: ./.github/workflows/ci.yml

  test-publish:
    needs: validate
    uses: ./.github/workflows/test-publish.yml
    with:
      bump_rule: ${{ inputs.bump_rule }}

  version-and-publish:
    needs: [validate, test-publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.29"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.12

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install bump2version
      run: uv tool install bump2version

    - name: Bump version
      run: |
        # If we have a dev version, strip it and use its base version
        if grep -q "\.dev[0-9]*$" pyproject.toml; then
          CURRENT_VERSION=$(bump2version --list ${{ inputs.bump_rule }} --dry-run | grep current_version | sed -r s,"^.*=",, )
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/\.dev[0-9]*$//')
          bump2version --allow-dirty --new-version $BASE_VERSION ${{ inputs.bump_rule }}
        else
          bump2version ${{ inputs.bump_rule }}
        fi
        git push
        git push --tags

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      run: uv publish

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        NEW_VERSION=$(python setup.py --version)
        gh release create "v${NEW_VERSION}" \
          --title "Release v${NEW_VERSION}" \
          --notes "Release v${NEW_VERSION}" \
          dist/*